import random
municipios_antioquia = [
    "Medellín",
    "Bello",
    "Itagüí",
    "Envigado",
    "Sabaneta",
    "Rionegro",
    "La Ceja",
    "Marinilla",
    "Copacabana",
    "Girardota",
    "Caldas",
    "La Estrella",
    "Sabaneta",
    "Amagá",
    "Guarne",
    "San Jerónimo",
    "Santa Fe de Antioquia",
    "Puerto Berrío",
    "Sonsón",
    "Jericó",
    "Andes",
    "Jardín",
    "Urrao",
    "Caucasia",
    "Apartadó",
    "Turbo",
    "Ituango",
    "Yarumal",
    "Valdivia",
    "Remedios",
    "Dabeiba",
    "El Bagre",
    "Zaragoza",
    "Puerto Nare",
    "Tarazá",
    "Segovia",
    "Vegachí",
    "Santo Domingo",
    "Anorí",
    "Cisneros",
    "San Pedro de los Milagros",
    "Santa Rosa de Osos",
    "Yalí",
    "San Andrés de Cuerquía",
    "Gómez Plata",
    "Yolombó",
    "Angostura",
    "Belmira",
    "Donmatías",
    "Santa Bárbara",
    "Santo Domingo",
    "El Peñol",
    "Granada",
    "San Rafael",
    "Concepción",
    "San Vicente",
    "El Santuario",
    "Guatapé",
    "Alejandría",
    "La Unión",
    "Cocorná",
    "Guadalupe",
    "Nariño",
    "Rionegro",
    "San Carlos",
    "San Francisco",
    "Carmen de Viboral",
    "La Unión",
    "El Carmen de Viboral",
    "Abejorral",
    "La Unión",
    "Sonsón",
    "Argelia",
    "Sonsón",
    "Nariño",
    "Salgar",
    "Cáceres",
    "Caucasia",
    "El Bagre",
    "Nechí",
    "Zaragoza",
    "San Roque",
    "Yarumal",
    "Valdivia",
    "Yalí",
    "Campamento",
    "Briceño",
    "Cisneros",
    "Yarumal",
    "San Andrés de Cuerquía",
    "Toledo",
    "Donmatías",
    "Girardota",
    "Barbosa",
    "Bello",
    "Medellín",
    "Itagüí",
    "Sabaneta",
    "La Estrella",
    "Caldas",
    "La Pintada",
    "Jericó",
    "Támesis",
    "Andes",
    "Jardín",
    "Santa Fe de Antioquia",
    "San Jerónimo",
    "Liborina",
    "Uramita",
    "Dabeiba",
    "Murindó",
    "Mutatá",
    "Chigorodó",
    "Carepa",
    "Apartadó",
    "San Juan de Urabá",
    "Arboletes",
    "Necoclí",
    "San Pedro de Urabá",
    "Turbo",
    "Vigía del Fuerte"
]

arboles_antioquia = [
    "Guayacán",
    "Ceiba",
    "Roble",
    "Pino",
    "Laurel",
    "Cedro",
    "Guanábana",
    "Mango",
    "Palma de cera",
    "Almendro",
    "Nogal",
    "Guacharaco",
    "Caucho",
    "Yarumo",
    "Arrayán",
    "Bambú",
    "Jacarandá",
    "Ficus",
    "Cascarillo",
    "Arrayán",
    "Papayo",
    "Guava",
    "Algarrobo",
    "Castaño",
    "Eucalipto",
    "Papaya",
    "Chagualo",
    "Pardillo",
    "Páramo",
    "Higuerón",
    "Palo de agua",
    "Nance",
    "Cilantro de monte",
    "Palo blanco",
    "Aromo",
    "Tamarindo",
    "Cafeto",
    "Aguacate",
    "Granadillo",
    "Tilo",
    "Higuerilla",
    "Pital",
    "Candelillo",
    "Guamo",
    "Chingalé",
    "Chorisia",
    "Piñuela",
    "Tamarindo",
    "Cuerno de alce",
]

cantidad = random.randint(100,5000)

# for i in range(2):
lista=random.choice(municipios_antioquia,arboles_antioquia)

